/*
AUTHOR: SHUBHAM KUMAR
CREATED ON: 03-Oct-2021
*/

-- CREATING TABLES
-- table1

CREATE TABLE stream
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name CHAR( 6 ),
    CONSTRAINT pk_stream_id PRIMARY KEY (id)
);

-- table2

CREATE TABLE student
(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  f_name VARCHAR( 255 ) NOT NULL,
  l_name VARCHAR( 255 ) NOT NULL,
  email VARCHAR( 255 ) NOT NULL,
  roll_no NUMBER NOT NULL,
  CONSTRAINT pk_student_id PRIMARY KEY (id)
);

-- ADDING COLUMNS TO table2

ALTER TABLE student ADD name VARCHAR( 32 ) NOT NULL;
ALTER TABLE student ADD stream NUMBER NOT NULL;

-- ADDING FOREIGN KEY CONSTRAINT TO table2

ALTER TABLE student ADD CONSTRAINT fk_stream_id FOREIGN KEY (stream) REFERENCES stream(id);

-- DROPPING COLUMNS FROM table2

ALTER TABLE student DROP COLUMN f_name;
ALTER TABLE student DROP COLUMN l_name;
ALTER TABLE student DROP COLUMN email;

-- INSERTING DATA IN table1

INSERT INTO stream(name) VALUES('BBA');
INSERT INTO stream(name) VALUES('BCA');
INSERT INTO stream(name) VALUES('BCOM');
INSERT INTO stream(name) VALUES('MCOM');
INSERT INTO stream(name) VALUES('MBA');
INSERT INTO stream(name) VALUES('MCA');
INSERT INTO stream(name) VALUES('BA');
INSERT INTO stream(name) VALUES('BSC');

-- INSERTING DATA IN table2

INSERT INTO student(roll_no, name, stream) SELECT 21, 'SUPERMAN TIWARI', stream.id FROM stream WHERE stream.name = 'MCA';
INSERT INTO student(roll_no, name, stream) SELECT 22, 'BATMAN SINGH', stream.id FROM stream WHERE stream.name = 'BCA';
INSERT INTO student(roll_no, name, stream) SELECT 78, 'SPIDERMAN DUBEY', stream.id FROM stream WHERE stream.name = 'MCOM';
INSERT INTO student(roll_no, name, stream) SELECT 67, 'IRONMAN KUMAR', stream.id FROM stream WHERE stream.name = 'BA';
INSERT INTO student(roll_no, name, stream) SELECT 73, 'CAP. AMERICA MISHRA', stream.id FROM stream WHERE stream.name = 'BCA';
INSERT INTO student(roll_no, name, stream) SELECT 31, 'BLACK WIDOW KHATOON', stream.id FROM stream WHERE stream.name = 'BCA';
INSERT INTO student(roll_no, name, stream) SELECT 43, 'WONDER WOMAN PANDEY', stream.id FROM stream WHERE stream.name = 'BCA';
INSERT INTO student(roll_no, name, stream) SELECT 42, 'CYBORG SHUKLA', stream.id FROM stream WHERE stream.name = 'BCA';
INSERT INTO student(roll_no, name, stream) SELECT 89, 'GILGAMESH', stream.id FROM stream WHERE stream.name = 'MBA';
INSERT INTO student(roll_no, name, stream) SELECT 77, 'FLASH THAKUR', stream.id FROM stream WHERE stream.name = 'BBA';
/*
INSERT INTO student(roll_no, name, stream) VALUES(21, 'SUPERMAN TIWARI', 'MCA');
INSERT INTO student(roll_no, name, stream) VALUES(22, 'BATMAN SINGH', 'BCA');
INSERT INTO student(roll_no, name, stream) VALUES(78, 'SPIDERMAN DUBEY','MCOM');
INSERT INTO student(roll_no, name, stream) VALUES(67, 'IRONMAN KUMAR','BA');
INSERT INTO student(roll_no, name, stream) VALUES(73, 'CAP. AMERICA MISHRA','BCA');
INSERT INTO student(roll_no, name, stream) VALUES(31, 'BLACK WIDOW KHATOON', 'BCA');
INSERT INTO student(roll_no, name, stream) VALUES(43, 'WONDER WOMAN PANDEY', 'BCA');
INSERT INTO student(roll_no, name, stream) VALUES(42, 'CYBORG SHUKLA', 'BCA');
INSERT INTO student(roll_no, name, stream) VALUES(89, 'GILGAMESH', 'MBA');
INSERT INTO student(roll_no, name, stream) VALUES(77, 'FLASH THAKUR', 'BBA');
*/

-- READING DATA

SELECT * FROM student;
SELECT * FROM stream;
SELECT LENGTH(stream) FROM student;
SELECT LENGTH(stream) FROM student WHERE name='CYBORG SHUKLA';
SELECT LENGTH(stream) FROM student WHERE name LIKE 'GILGAMESH';
SELECT LENGTH(stream) FROM student WHERE name LIKE UPPER('flash thakur');
SELECT LENGTH(name) FROM student;
SELECT MAX(name) FROM student;
SELECT MIN(name) FROM student;

SELECT name FROM student WHERE roll_no IN (SELECT MAX(roll_no) FROM student);
SELECT name FROM student WHERE roll_no IN (SELECT MIN(roll_no) FROM student);

-- UPDATING RECORD IN table2

UPDATE student SET name=UPPER('ironman patel') WHERE name LIKE UPPER('ironman kumar');
-- UPDATE student SET stream=UPPER('bba') WHERE name LIKE 'IRONMAN PATEL';
SELECT * FROM student;


-- UPDATE student SET stream=1;

-- ADDING CONSTRAINTS

-- ALTER TABLE student MODIFY stream NUMBER NOT NULL;
-- ALTER TABLE student ADD CONSTRAINT pk_student_id PRIMARY KEY (id);
-- ALTER TABLE stream ADD CONSTRAINT pk_stream_id PRIMARY KEY (id);


/*
-- FORMATTING REPORT

SET linesize 180;
COLUMN student.id HEADING 'STUDENT|ID';
COLUMN stream.name HEADING 'STREAM|NAME';
COLUMN student.stream HEADING 'STREAM|ID';
*/

-- READING DATA AFTER JOINING BOTH TABLES

SELECT student.id, roll_no, student.name, student.stream, stream.name FROM student JOIN stream ON student.stream = stream.id;

-- COMMITING CHANGE

COMMIT;